# Generated by Django 2.0.3 on 2018-04-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roughdata',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
