# Generated by Django 2.1.7 on 2019-06-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_roughdata_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='roughdata',
            name='firstletter',
            field=models.CharField(default='', max_length=255),
        ),
    ]
