# Generated by Django 2.2.13 on 2020-08-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_roughdata_firstletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='roughdata',
            name='cohort',
            field=models.CharField(default='', max_length=100),
        ),
    ]
