# Generated by Django 2.2.13 on 2021-12-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_roughdata_cohort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roughdata',
            name='firstletter',
        ),
        migrations.RemoveField(
            model_name='roughdata',
            name='lastfive',
        ),
        migrations.AddField(
            model_name='roughdata',
            name='subid',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roughdata',
            name='timepoint',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
    ]
